apiVersion: v1
kind: Namespace
metadata:
  name: nginx-tcp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-tcp-ingress-sa
  namespace: nginx-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tcp-ingress-controller
  namespace: nginx-tcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tcp-ingress
  template:
    metadata:
      labels:
        app: nginx-tcp-ingress
    spec:
      serviceAccountName: nginx-tcp-ingress-sa
      containers:
      - name: nginx-tcp-ingress-controller
        image: registry.k8s.io/ingress-nginx/controller:v1.11.1
        args:
          - /nginx-ingress-controller
          - --ingress-class=nginx-tcp
          - --election-id=ingress-controller-leader-tcp
          - --controller-class=k8s.io/ingress-nginx
          - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
          - --publish-service=$(POD_NAMESPACE)/nginx-tcp-service
        ports:
        - name: bolt-https
          containerPort: 7473
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: nginx-tcp
data:
  "7473": "default/neo4j-service:7473"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-tcp-service
  namespace: nginx-tcp
spec:
  type: NodePort
  selector:
    app: nginx-tcp-ingress
  ports:
  - name: bolt-https
    port: 7473
    targetPort: 7473
    nodePort: 30743
