apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-serviceaccount
  namespace: ingress-nginx-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      containers:
      - name: nginx-ingress-controller
        image: registry.k8s.io/ingress-nginx/controller:v1.11.1
        args:
          - /nginx-ingress-controller
          - --ingress-class=nginx
          - --election-id=ingress-controller-leader
          - --controller-class=k8s.io/ingress-nginx
          - --watch-ingress-without-class=true
          - --publish-service=$(POD_NAMESPACE)/nginx-ingress-service
        ports:
        # - name: http
        #   containerPort: 80
        - name: https
          containerPort: 443
        - name: bolt
          containerPort: 7687
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-service
  namespace: ingress-nginx-v1
spec:
  type: NodePort
  selector:
    app: nginx-ingress
  ports:
  # - name: http
  #   port: 80
  #   targetPort: 80
  #   nodePort: 30080
  - name: jdbc-tcp
    port: 443
    targetPort: 443
    nodePort: 30443
  - name: bolt-tcp
    port: 7687
    targetPort: 7687
    nodePort: 30687
