apiVersion: v1
kind: Namespace
metadata:
  name: nginx-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tcp-ingress-controller
  namespace: nginx-tcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tcp-ingress
  template:
    metadata:
      labels:
        app: nginx-tcp-ingress
    spec:
      containers:
      - name: nginx-tcp-ingress-controller
        image: nginx/nginx-ingress:2.4.2
        args:
          - -nginx-plus=false
          - -nginx-configmaps=$(POD_NAMESPACE)/tcp-services
        ports:
        - name: bolt-https
          containerPort: 7473
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: nginx-tcp
data:
  "7473": "default/neo4j-service:7473"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-tcp-service
  namespace: nginx-tcp
spec:
  type: NodePort
  selector:
    app: nginx-tcp-ingress
  ports:
  - name: bolt-https
    port: 7473
    targetPort: 7473
    nodePort: 30743
