apiVersion: v1
kind: Namespace
metadata:
  name: nginx-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tcp-ingress-controller
  namespace: nginx-tcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tcp-ingress
  template:
    metadata:
      labels:
        app: nginx-tcp-ingress
    spec:
      containers:
      - name: nginx-tcp-ingress-controller
        image: nginx/nginx-ingress:2.4.2
        args:
          - -nginx-plus=false
          - -nginx-configmaps=$(POD_NAMESPACE)/tcp-services
        ports:
        - name: tcp
          containerPort: 3306  # Example: expose MySQL
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: nginx-tcp
data:
  "3306": "default/mysql-service:3306"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-tcp-service
  namespace: nginx-tcp
spec:
  type: NodePort
  selector:
    app: nginx-tcp-ingress
  ports:
  - name: tcp
    port: 3306
    targetPort: 3306
    nodePort: 30306
