apiVersion: v1
kind: Namespace
metadata:
  name: neo4j
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:5.9
        ports:
        - containerPort: 7687  # Bolt TCP
        - containerPort: 7473  # Bolt HTTPS
        env:
        - name: NEO4J_AUTH
          value: "neo4j/test"  # username/password
